version: '3.8'
services:
  db:
    image: postgres:15
    container_name: wardrobe-db
    environment:
      POSTGRES_DB: wardrobe
      POSTGRES_USER: wardrobe
      POSTGRES_PASSWORD: wardrobe
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
