FROM maven:3.9.8-eclipse-temurin-17

WORKDIR /app

# Копируем pom.xml и загружаем зависимости
COPY pom.xml .
RUN mvn dependency:go-offline -B

# Копируем исходный код
COPY src ./src

# Запускаем тесты (команда переопределяется в docker-compose.yml)
CMD ["mvn", "test"]

