spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/wardrobe}
    username: ${DB_USER:wardrobe}
    password: ${DB_PASSWORD:wardrobe}
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: ${PORT:8080}
